import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  devopsSidebar: [{ type: 'autogenerated', dirName: 'devops' }],
  infrastructureSidebar: [{ type: 'autogenerated', dirName: 'infrastructure' }],
  securitySidebar: [{ type: 'autogenerated', dirName: 'security' }],
  architectureSidebar: [{ type: 'autogenerated', dirName: 'architecture' }],
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
export default sidebars;
